version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/var/api
      - /var/api/node_modules
    # port 3000 has to match src/proxy.conf.json
    ports:
      - 3030:3030
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb--vol:/data/db
      - ./api/_docker:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  mongodb--vol:
