version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/var/api
      - /var/api/node_modules
    # port 3000 has to match src/proxy.conf.json
    ports:
      - 3030:3030
    depends_on:
      - mongo

  mongo:
    image: mongo
